alias la="ls -a"
alias rf="rm -rf"

alias stdin="/dev/stdin"
alias stdout="/dev/stdout"
alias zero="/dev/zero"
alias bits="/dev/bits"
alias null="/dev/null"
alias q='exit'
alias h='history'
alias cs='clear;ls'
alias p='cat'
alias rma='rm -rf'
alias la='ls -a'
alias repos='cd /repos/'
alias t='time'
alias k='kill'
alias unlock='chmod -R 755'
alias python='python3'
alias venv='source /.venv/bin/activate'
alias home='cd ~'
alias root='cd /'
alias edit='nvim'
alias pip='pipx'
alias gentags='ctags -R .'
alias ssh-gh-test='ssh -T git@github.com'
alias git-save='git add * && git commit -a -m "auto-commit"'
alias git-update='git-save && git push'
alias runescape="flatpak run com.adamcake.Bolt"
