alias la="ls -a"
alias delete="rm -rf"
alias dirinfo=". /sh/dirinfo.sh"
alias null="/dev/null"
alias stdin="/dev/stdin"
alias stdout="/dev/stdout"
alias zero="/dev/zero"
alias bits="/dev/bits"
alias q='exit'
alias clr='clear'
alias h='history'
alias cs='clear;ls'
alias p='cat'
alias rma='rm -rf'
alias la='ls -a'
alias repos='cd /repos/'
alias t='time'
alias k='kill'
alias unlock='chmod -R 755'
alias python='python3'
alias null='/dev/null'
alias venv='source /.venv/bin/activate'
alias home='cd ~'
alias root='cd /'
alias edit='nvim'
alias gentags='ctags -R .'
alias ssh-gh-test='ssh -T git@github.com'
alias gupdate='git add * && git commit * && git push'
alias runescape="flatpak run com.adamcake.Bolt"
