. ~/bash/config/.inputrc
. ~/bash/config/startup.sh
. ~/bash/config/aliases.sh
. ~/bash/config/completion.sh
. ~/bash/config/env.sh
export PS1='\u$'
figlet -cl "Welcome TGN"
neofetch
# Global file 
if [ -f /etc/bashrc]; then 
  . /etc/bashrc 
fi
export HISTSIZE = 10000
export PATH=$PATH:/usr/local/go/bin
export PATH="$PATH:/opt/nvim/"
export PATH=/home${USER}/salt:$PATH 
export SALT_SALTFILE=/home/${USER}/salt/Saltfile
